### ISSUE TITLE
Update mocha instructions

### ISSUE THREAD

**Issue by taoeffect** [benbria/coffee-coverage#36]
The command listed didn't work for me at all:

     mocha --require coffee-coverage/register --reporter html-cov > coverage.html

This, on the other hand, did:

     mocha --require coffee-coverage/register --compilers coffee:coffee-script/register -R html-cov --bail test/ > coverage.html

My source is in `src/` and tests are in `test/`.

**Comment by Dashed** [comment]
Thanks for posting a solution on [Stackoverflow](http://stackoverflow.com/a/28576695/412627) and on here. I marked your answer on SO as an accepted answer.

I haven't really tested your solution; but I trust you that it should work for others :wink: 

----

I've since moved on to babel (6to5) instead of CoffeeScript; since tooling in ES6+ land is better.

**Comment by taoeffect** [comment]
Thanks @Dashed, and cute avatar. :+1:

**Comment by jwalton** [comment]
Thanks @taoeffect.  Fixed in master via 160970ffc0fedd8a24905b2f803904c231859771.
