### ISSUE TITLE
Pragmas and Block Comments

### ISSUE THREAD

**Issue by silkentrance** [benbria/coffee-coverage#40]
While the pragma feature is cool, these comments will be retained in the generated code:

```
Block comments, which mirror the syntax for block strings, are preserved in the generated code.
````

From my experiments with coffedoc and the "AST" written out by the coffee compiler, OTOH I think that that all documentation will be associated with the node immediately following that documentation.
Would it not be better to parse that documentation instead of leaking these pragmas into the generated code?

**Comment by silkentrance** [comment]
For an example, see
https://github.com/omarkhan/coffeedoc/blob/master/src/coffeedoc.coffee#L147

**Comment by jwalton** [comment]
Hmm...  We can solve the doc problem by making the the pragma apply to the next non-comment block, instead of the next block:

    ### !pragma coverage-skip ###
    ### Doc string goes here ###
   partyCat = (x) -> "It's party time."

It would be nice if the pragmas didn't make it down into the generated JS code, but unfortunately a non-block comment gets dropped by the coffee-script compiler before it makes it to the AST, so the instrumentor will never even see it.  We could delete the pragma comment while compiling, but this only helps when you're instrumenting; the comment will still be there if you compile without instrumentation, which is the case you actually care about.

I was also considering using bare strings for pragmas:

    "!pragma coverage-skip"
   partyCat = (x) -> "Forever!"

This was inspired by the `"use strict";` pragma from JavaScript.  The advantage of the block-comment based version is it will get removed by a minifier (the bare string version might, I suppose, depending on how clever your minfier is, but the comment will for sure) so at least the pragmas won't make it down to a client.  Also, the block comment was closer to what [istanbul does](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md).

**Comment by jwalton** [comment]
Another option would be to use line comments:

    # !pragma coverage-skip
    partyCat = (x) -> "Party party!"

and then scan the original source for these, and try to figure out which statement they apply to using line numbers...  But, ugh.  :worried:

**Comment by silkentrance** [comment]
Actually, these inline comments are part of the AST and will be collected in form of a single multi line string and then attached to the next, non comment node, found on the current indentation level as its comment property. Parsing that string should work out fine, I presume.

BTW nicely done. My solution would have been more complicated, so kudos to you for that!

**Comment by jwalton** [comment]
Wow, really?  That's cool!  I'll check this out.  Thanks @silkentrance.  :)

**Comment by silkentrance** [comment]
@jwalton did you look at the links provided in https://github.com/benbria/coffee-coverage/issues/40#issuecomment-98842966, yet?

**Comment by jwalton** [comment]
I did; the `.comment` they are grabbing here is actually from a [Comment node](https://github.com/jashkenas/coffeescript/blob/master/src/nodes.coffee#L580-L581), though.

**Comment by silkentrance** [comment]
@jwalton Silly me. I meant to refer to codo instead of coffeedoc.

https://github.com/coffeedoc/codo/blob/master/lib/traverser.coffee#L45

**Comment by silkentrance** [comment]
@jwalton Are you working on this or may I provide you with a PR for this one?

**Comment by silkentrance** [comment]
I have hacked up a solution that will replace all !pragma / istanbul ignore single line comments with herecomments. I am still trying to find a way to actually test this automatically.
