### ISSUE TITLE
electron-mocha support

### ISSUE THREAD

**Issue by dustinblackman** [benbria/coffee-coverage#60]
Currently trying to run istanbul tests with [electron-mocha](https://github.com/jprichardson/electron-mocha) but am getting 0% coverage when it should be ~50%. Willing to do a PR myself if I can get pointed in the right direction.

**Comment by jwalton** [comment]
I would welcome a PR for sure.  electron-mocha looks pretty cool.  :)

There's documentation about how this all works [here](https://github.com/benbria/coffee-coverage/blob/master/docs/development.md).  I just wrote it, so if anything is unclear, please feel free to ask questions.  If I had to make an educated guess as to what's going on here, I would hazard to guess that electron-mocha is spawning a child process to run tests in, in electron.  Since coffee-coverage stores all instrumentation data in a global variable, this can cause problems if the contents of that global variable aren't being propagated from one process to the other.

If this is what's going on then offhand I have a couple of... kinda terrible ideas about how to solve this.  :P  But I'll let you explore a bit, because maybe you'll come up with something better.  :)

**Comment by dustinblackman** [comment]
Thanks for the input! I'll see about taking a crack at it sometime next week if I can make the time.

**Comment by dustinblackman** [comment]
This turned out to be an issue on electron mochas end, will be putting up a pr there. Thanks again.
