### ISSUE TITLE
When doing a Mongoose mapReduce a ReferenceError is thrown

### ISSUE THREAD

**Issue by bcallaars** [benbria/coffee-coverage#67]
I'm having a hard time finding out where my Mongoose `mapReduce` is going wrong, but the following error keeps occurring _only_ when we have `coffee-coverage` on:

`[MongoError: exception: ReferenceError: _$coffeeIstanbul is not defined near '_$coffeeIstanbul['`

And then just a path. 

The command I am running is:

`NODE_ENV=test mocha --require coffee-script/register --require coffee-coverage/register-istanbul --compilers coffee:coffee-script/register --require should --check-leaks --reporter spec test/unit/ test/e2e/`

Am I missing something or is this a genuine bug?

**Comment by jwalton** [comment]
Yeah, I ran into this too.  :)

`coffee-coverage` instruments the code; to over-simplify, we have a global variable that holds the number of times every line has been executed, and the in the code we add a bunch of `_$coffeeIstanbul[27]++` statements.  The problem here is that Mongoose is actually going to take your function, serialize it, send it to MongoDB, and then MongoDB will run it.  When that happens, the global variable doesn't exist in MongoDB's context, so when we try to increment the count, you run into this problem.

The easiest way to get around this is to use a [`### !pragma no-coverage-next ###`](https://github.com/benbria/coffee-coverage/blob/master/docs/pragmas.md#-pragma-no-coverage-next-) pragma, so your map-reduce code doesn't get instrumented.

Feel free to re-open if this doesn't solve your problem.  :)

**Comment by bcallaars** [comment]
Thanks!

**Comment by rudolph9** [comment]
This was super helpful as I was running into this issue do to my lint script.  I was getting the following:

```
     MongoError: ReferenceError: cov_fs4ihtlo3 is not defined :
@:2:7
```

I put `/* istanbul ignore next */` before my function calling `mapReduce` and that fixed it.
